### ISSUE TITLE
Korrektur des FIWARE-Models zur korrekten, sensor-basierten Speicherung der Daten der Sensoren

### ISSUE THREAD

**Issue by saschadoemer** [vitrum-connect/5gla-api#124]
**Beschreibung**

Als Entwickler möchte ich das FIWARE-Modell so anpassen, dass es die Daten von Sensoren korrekt und effizient speichert, um die Genauigkeit und Zuverlässigkeit der Datenerfassung zu verbessern. Dies soll durch die Optimierung der Datenstruktur und des Speicherformats erreicht werden, um die Integration und Analyse von Sensordaten in Echtzeit zu ermöglichen.

**Akzeptanzkriterien**

Damit die User Story erfolgreich umgesetzt ist, wird erwartet:

- ... dass das angepasste FIWARE-Modell alle relevanten Sensortypen unterstützt.
- ... dass die Datenstruktur und das Speicherformat so optimiert sind, dass sie eine schnelle Erfassung und Abfrage von Sensordaten ermöglichen.
- ... dass das System die Integrität und Genauigkeit der gespeicherten Daten gewährleistet.
- ... dass die Lösung skalierbar ist und mit der Zunahme der Sensoren und Datenmengen effizient umgehen kann.
- ... dass die Dokumentation des angepassten Modells aktualisiert wird, um die Änderungen und deren Auswirkungen auf die Datenspeicherung und -abfrage zu erläutern.
- ... dass Tests durchgeführt werden, um die korrekte Funktion des angepassten Modells zu verifizieren und sicherzustellen, dass keine negativen Auswirkungen auf bestehende Funktionen entstehen.

**Comment by saschadoemer** [comment]
Geschlossen mit https://github.com/vitrum-connect/5gla-cluster-config/pull/62

**Comment by Chromeggs** [comment]
Heute angefragt, ob Hilfe benötigt wird, oder ob das ggf. noch mal in kleinere Teile zerlegt werden sollte (due date lag auf 23.02.2024)
