### ISSUE TITLE
Anlage eines Schlags für einen spezifischen Tenant mithilfe eines dedizierten Endpunktes in der API

### ISSUE THREAD

**Issue by saschadoemer** [vitrum-connect/5gla-api#149]
**Beschreibung**

Als Entwickler möchte ich einen dedizierten Endpunkt in unserer API implementieren, der es ermöglicht, einen neuen Schlag (z.B. eine Kategorie oder eine thematische Einheit) für einen bestimmten Tenant zu erstellen.  Der Endpunkt soll die erforderlichen Daten entgegennehmen und einen neuen Schlag entsprechend diesen Daten anlegen.

**Akzeptanzkriterien**

Damit die User Story erfolgreich umgesetzt ist, wird erwartet:

- ... dass der Endpunkt eine Methode zur Übermittlung der erforderlichen Daten für die Anlage eines Schlages bereitstellt.
- ... dass der Endpunkt eine Authentifizierung und Autorisierung des Benutzers erfordert, um sicherzustellen, dass nur berechtigte Nutzer einen Schlag anlegen können.
- ... dass bei erfolgreichem Anlegen eines Schlages eine Bestätigung zusammen mit den Details des neu angelegten Schlages zurückgegeben wird.
- ... dass im Falle fehlender oder ungültiger Eingabedaten eine entsprechende Fehlermeldung zurückgegeben wird, die den Benutzer darüber informiert, welche Korrekturen erforderlich sind.

**Comment by saschadoemer** [comment]
Änderungen in https://github.com/vitrum-connect/5gla-fiware-integration-layer/pull/52 sind notwendig, damit die Daten geolokalisiert gespeichert werden.

**Comment by saschadoemer** [comment]
Aktuell in Verzug wg. Krankheit und Konferenz, Datum auf den 12.04. gesetzt.

**Comment by saschadoemer** [comment]
Am Freitag leider nicht fertig geworden, daher **neues Datum auf den 15.04. gesetzt**.

**Comment by Chromeggs** [comment]
Hey dude: delivery date Apr 15
Was geht?

**Comment by saschadoemer** [comment]
Ja, ich bin weit dahinter, wird diese Woche wirklich, wirklich fertig. Wäre mir sonst auch schon zu unangenehm.
