### ISSUE TITLE
Geolokalisierte Speicherung des Schlags zur späteren Visualisierung in QGIS

### ISSUE THREAD

**Issue by saschadoemer** [vitrum-connect/5gla-api#150]
**Beschreibung**

Als ein Nutzer, der Felddaten analysiert, möchte ich den genauen Standort eines jeden Schlags, den ich besuche oder analysiere, speichern können, um diese Daten später in QGIS zu visualisieren und geografisch zu analysieren.  Ich möchte in der Lage sein, diese geolokalisierten Daten direkt aus meiner mobilen Anwendung oder meinem Datenerfassungssystem zu exportieren und in QGIS zu importieren, ohne manuelle Konvertierungen oder Anpassungen vornehmen zu müssen.

**Akzeptanzkriterien**

Damit die User Story erfolgreich umgesetzt ist, wird erwartet ...

- ... dass der Nutzer die Option hat, zusätzliche Informationen zum Schlag, wie etwa den Namen oder spezifische Merkmale, zusammen mit den geolokalisierten Daten zu speichern.
- ... dass die gespeicherten Daten in einem Format vorliegen, das direkt in QGIS importiert werden kann, ohne dass eine vorherige Konvertierung oder Bearbeitung erforderlich ist.

**Comment by Chromeggs** [comment]
Moin @saschadoemer, 
Diese UserStory fragt nach einem Datum, an dem sie ausgeliefert werden will.
😇
LG Ben
