### ISSUE TITLE
Anbindung der OpenWeather API zur periodischen Abfrage von historischen Wetterdaten innerhalb der bestehenden Anwendung

### ISSUE THREAD

**Issue by saschadoemer** [vitrum-connect/5gla-api#222]
**Beschreibung**

Als Entwickler möchte ich eine Anbindung der OpenWeather API integrieren, um periodisch historische Wetterdaten innerhalb der bestehenden Anwendung abzufragen. Dadurch können die Nutzer der Anwendung Zugriff auf relevante Wetterinformationen aus der Vergangenheit erhalten, die für Analysen oder Berichte verwendet werden können.

**Akzeptanzkriterien**

Damit die User Story erfolgreich umgesetzt ist, wird erwartet ...

- ... dass die API-Anbindung stabil und fehlerfrei funktioniert.
- ... dass die historischen Wetterdaten in regelmäßigen Abständen automatisch abgerufen werden.
- ... dass die abgerufenen Daten korrekt und vollständig in der Anwendung gespeichert werden.

**Funktionale Anforderungen**

- API-Schlüsselkonfiguration zur Authentifizierung bei OpenWeather.
- Einrichtung eines Zeitplans für die automatische Abfrage der historischen Wetterdaten.
- Implementierung einer Datenverarbeitungsroutine zum Speichern der abgerufenen Daten in der Datenbank.

**Comment by saschadoemer** [comment]
@Chromeggs die API ist ja, anders als die vorherigen Importe, zentral verfügbar, d.h. ohne nutzerspezifische Daten. Damit steht die API als Querschnitt für alle Nutzer zur Verfügung, korrekt? Oder soll die Möglichkeit bestehen, dass die Datenmenge später pro Nutzer abgerechnet wird, dann müssen wir pro Tenant einen API-Key erzeugen, mit dem wir auf die API zugreifen.

**Comment by saschadoemer** [comment]
@Chromeggs wie besprochen, API-Key pro Tenant.

**Comment by Chromeggs** [comment]
Yep!

**Comment by saschadoemer** [comment]
Datum angepasst wg. fachlicher und technischer Klärung.

**Comment by saschadoemer** [comment]
@Chromeggs welchen Bezugspunkt soll die Abfrage der Wetterdaten haben? Pro lokalisiertem Sensor oder hast du eine andere Referenz? Soll das automatisch der Fall sein, oder soll der Nutzer die Abfragen selber registrieren müssen? Ich glaube, es ist sinnvoll, wenn der Nutzer die Abfragen selber registriert, damit wir keinen Automatismus integrieren, der dann wieder pro Sensor aktiviert / deaktiviert werden muss.

**Comment by Chromeggs** [comment]
Moin @saschadoemer, 
"Bezugspunkt" ist geographisch? Zeitlich? Beides?
Um die Frage nach der Automatisierung sinnvoll beantowrten zu können, müsste ich verstehen:
1. Wofür brauchen wir oder jemand anders die Wetterdaten konkret? (ich weiß, die Frage muss ich mir vor allem selbst stellen, aber zu zweit sind wir halt unschlagbar 🤤, z.B.: unser KI-UseCase? / Frontend-Visualisierungen via QGIS? /  zukünftige KI-Cases über heute gesammelte Daten? 
2. Welche Daten genau können in dem Call abgerufen werden?
3. Wie groß ist der Speicherbedarf pro Call?
4. Welche constraints gibt es für die Abrufe seitens OpenWeather? (z.B. Kosten)
5. Sind historische Abrufe im Verghleich zu live-Abrufen in irgendeiner Weise limitiert?
Grundsätzlich stelle ich mir vor, dass ein geschulter Sysadmin (oder eine gute KI) zukünftig die Aufgabe übernehmen könnte, die Abfragen je nach Anwendungsfalls zu konfigurieren. 
Vieles davon haben wir glaube ich auch schon angesprochen, aber ich bin nicht sicher, ob wir es auch festgehalten haben.
Was sagst du?
LG Ben

**Comment by Chromeggs** [comment]
Moin @saschadoemer ,
Kommst du voran mit der OW-Anbindung?
Ich habe ja letzte Woche tausend Fragen zurück gestellt, um deine zwei Fragen zu beantworten.
Ggf kann man die aber auch alle als "rhetorisch" interpretieren, und du kommst damit zurecht?
Let me know falls du weiteren Input brauchst oder Abstimmungsbedarf hast, ok?
LG Ben

**Comment by Chromeggs** [comment]
Moin @saschadoemer : any progress beim Thema OpenWeather, der hier dokumentiert werden könnte/sollte?
Bin gespannt (eines meiner Lieblingsthemen...).
LG Ben

**Comment by saschadoemer** [comment]
@Chromeggs not yet, die Vorbereitung auf die Drohnenflüge hat Zeit gefressen. 

Zu deinen Fragen:

1) Daten aus der Vergangenheit, d.h. aktuelle Wetterdaten des Tages als Dokumentation aus der Vergangenheit oder auch der initiale Import in die eigene Datenbank als Basis für die Datenlage zum Lernen.

2) Ich würde die historischen Daten abfragen, d.h. alle Daten aus diesem Call hier > https://openweathermap.org/api/one-call-3#history

3) Gering, wenige KB.

4)  Siehe folgenden Screenshot.

![Image](https://github.com/user-attachments/assets/efad938e-3be1-459d-9ece-de1279fadf45)

5) Bis zu 45 Jahre in die Vergangenheit als einzige Limitierung.

**Comment by saschadoemer** [comment]
Aktuelle Umsetzung für einen ersten Draft:

- Registrieren eines Sensors in der Anwendung
- Automatischer, stündliche Abfrage der aktuellen Wetterdaten für die Position des Sensors.

**Comment by saschadoemer** [comment]
@DomenikINBW kannst du mir den Link zur Integration der Campus-Wetterstation schicken bzw. hier ergänzen?

**Comment by saschadoemer** [comment]
Import aus der Vergangenheit mit dem folgenden PR.

#227

**Comment by saschadoemer** [comment]
Fiware Integration mit dem folgenden PR.

#228

**Comment by DomenikINBW** [comment]
> @DomenikINBW kannst du mir den Link zur Integration der Campus-Wetterstation schicken bzw. hier ergänzen?

Wetterstation ist von 1994. Der Datenlogger ist an einen Rechner Angeschlossen auf den Olaf per remote Desktop zugreift. Mit der Steuersoftware fragt er dann die Werte des letzten Monats als xls ab und speichert diese. Soweit ich das sehe gibt es keine API.
