### ISSUE TITLE
Initialer Import einer Schlagkartei | GeoJSON

### ISSUE THREAD

**Issue by saschadoemer** [vitrum-connect/5gla-api#99]
**Beschreibung:**

Als Landwirt möchte ich, dass eine Schnittstelle zur Verfügung gestellt wird bei der GeoJSON-Datein initial importiert werden können, damit ich meine Schlagdatein nicht neu erstellen muss.

**Zusammengefasste Zielsetzung:**

-     Bereitstellung einer Schnittstelle für den initialen Import einer Schlagdatei.

**Akzeptanzkriterien:**

Die User Story ist erfolgreich umgesetzt, wenn...

-     eine Schnittstelle für den initialen Import von einer Schlagdatei bereitgestellt wurde.

**Comment by saschadoemer** [comment]
@Jonasstemme @Vitrum-LL @Chromeggs ich schließe alles, was nicht Polygon ist, erstmal aus 👌🏼

**Comment by Chromeggs** [comment]
@saschadoemer : und ist GeoJSON polygon oder nicht?

**Comment by saschadoemer** [comment]
GeoJSON kann viel mehr als Polygon, d.h. Point, LineString, MultiPoint, MultiLineString, Multipolygon. Für einen Schlag sollte aber Polygon reichen. Alles andere kann bei Bedarf nachgezogen werden.
